---
title: "Results_WordSim353"
author: "Fleur Petit"
date: "11 February 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('tidyverse')
library('knitr')
```

## Function to load the data

```{r}

loadData <- function() {
  files <- list.files(file.path("./results"), full.names = TRUE)
  data <- do.call(rbind, lapply(files, read.csv)) %>%
    drop_na()
  as_tibble(data)
}
```

## Table with all the results

```{r}
df <- loadData()
kable(t(df))

```

## Function to calculate the 95% confidence interval

```{r}

ci <- function(mean, sd, n){
  error <- qnorm(0.975)*sd/sqrt(n)
  lower <- mean-error
  upper <- mean+error
  return(tibble(lower = lower,upper = upper))
}
```

## Mean, standard deviation, lower and upper 95% confidence interval, median

```{r}

description <-
  df %>%
  gather(key = "word_pair", value = "similarity") %>%
  group_by(word_pair) %>%
  mutate(mean = mean(similarity),
            sd = sd(similarity),
            lower = ci(mean,sd,nrow(df))[["lower"]],
            upper = ci(mean,sd,nrow(df))[["upper"]],
            median = median(similarity)
            )

description %>% 
  group_by(word_pair, mean, sd, lower, upper, median) %>% 
  summarise() %>% 
  kable()

```

## Density plots with mean and 95% confidence interval

```{r}

ggplot(description, aes(similarity)) +
  geom_density() +
  facet_wrap(~ word_pair) +
  geom_vline(aes(xintercept = mean), colour = "red", linetype = "dashed") +
  geom_vline(aes(xintercept = lower), linetype = "dashed") +
  geom_vline(aes(xintercept = upper), linetype = "dashed")
  

```

## Pairs with a relatively large spread

A sd > 2.5 has been chosen arbitrarily to indicate a relatively large spread.

```{r}

description %>%
  group_by(word_pair, sd) %>%
  summarise() %>%
  filter(sd > 2.5) %>%
  arrange(sd) %>%
  kable()

```